assets:
  settings.xml: "yegor256/home#assets/thindeck/settings.xml"
  pubring.gpg: "yegor256/home#assets/pubring.gpg"
  secring.gpg: "yegor256/home#assets/secring.gpg"

deploy:
  env:
    MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"
  script:
    - "sudo apt-get install -y openjdk-6-jre"
    - "wget --retry-connrefused http://yar.fruct.org/attachments/download/362/plantuml_7707-1_all.deb"
    - "sudo dpkg -i plantuml_7707-1_all.deb"
    - "wget --retry-connrefused https://oss.sonatype.org/content/repositories/releases/net/sourceforge/plantuml/plantuml/8000/plantuml-8000.jar"
    - "mv plantuml-8000.jar /usr/share/plantuml/plantuml.jar"
    - "sudo bundle"
    - "mvn clean test deploy -Ppdd -Pqulice --errors --settings ../settings.xml"
    - "mvn clean site-deploy -Psite -Prempl --errors --settings ../settings.xml"

merge:
  env:
    MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"
  script:
    - "mvn clean install -Pqulice --errors --settings ../settings.xml"

release:
  env:
    MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"
  script:
    - "mvn versions:set \"-DnewVersion=${tag}\""
    - "git commit -am \"${tag}\""
    - "mvn clean deploy -Pqulice -Psonatype -Pthindeck --errors --settings ../settings.xml"
